# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.2
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: 58363638+A-Maugli@users.noreply.github.com
author_name: A-Maugli
cloud_provider: none
contract_name: biz_kor
preset_name: production
project_name: biz_kor

